CREATE TABLE book_readers (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    is_active BIT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);